lint:
  actions_awsfulltest: false
  actions_awstest: false
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-variant2qtl_logo_light.png
    - docs/images/nf-core-variant2qtl_logo_light.png
    - docs/images/nf-core-variant2qtl_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
  files_unchanged: false
  multiqc_config:
    - report_comment
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - manifest.version
  nfcore_components: false
  readme: false
nf_core_version: 4.1.0
repository_type: pipeline
template:
  author: siyangming
  description: An end-to-end, multi-entry Nextflow pipeline for comprehensive QTL
    (eQTL/sQTL/pQTL) analysis, integrating diverse genetic variants (SNPs, Indels,
    STRs, and SVs) with automated functional annotation.
  force: false
  is_nfcore: false
  name: variant2qtl
  org: SiYangming
  outdir: .
  skip_features: []
  version: 0.0.1dev
