# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "QTL_TWAS"
description: FUSION/PrediXcan/MetaXcan-style TWAS from gene weights (TSV or PredictDB) and GWAS sumstats
components:
  - TWAS_PREDICTDB
  - TWAS_FUSION
input:
  - ch_weights
  - ch_gwas
  - ch_ld
output:
  - twas
  - outdir
  - versions
authors:
  - "@SiYangming"
