# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "QTL_LDSC"
description: LD-score regression style heritability and partitioned enrichment
components:
  - LDSC_H2
input:
  - ch_sumstats
  - ch_annot
  - ch_ldscores
output:
  - h2
  - partitioned
  - outdir
  - versions
authors:
  - "@SiYangming"
