# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "GENOTYPE_TO_ANALYSIS_FORMAT"
description: Passthrough PLINK bed and optional VCF→BGEN for molQTL engines
keywords:
  - gwas
  - qtl
  - local
components: []
input: []
output: []
authors:
  - "@SiYangming"
maintainers:
  - "@SiYangming"
