# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "VARIANT_ANNOTATE"
description: Annotate VCF with optional vcfanno overlay then Ensembl VEP and/or snpEff (scatter-gather)
components:
  - VCFANNO
  - VCF_ANNOTATE_ENSEMBLVEP_SNPEFF
  - VCF_FILTER_BCFTOOLS_ENSEMBLVEP
input:
  - ch_vcf
  - ch_fasta
  - ch_vep_cache
  - ch_snpeff_cache
output:
  - vcf
  - versions
authors:
  - "@SiYangming"
