---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "QTL_COLOC"
description: Local subworkflow qtl_coloc for SiYangming/variant2qtl
keywords:
  - qtl
  - gwas
  - coloc
  - local
components:
  - coloc/abf
input: []
output: []
authors:
  - "@SiYangming"
maintainers:
  - "@SiYangming"
